Name: onPushToMainDeploymentWorkflow
SchemaVersion: "1.0"
Triggers:
  - Type: PUSH
    Branches:
      - main
Actions:
  BuildAndTest:
    Identifier: aws/managed-test@v1
    Inputs:
      Sources:
        - WorkflowSource
    Outputs:
      AutoDiscoverReports:
        IncludePaths:
          - "**/*"
        ExcludePaths:
          - "*/.aws/workflows/*"
        ReportNamePrefix: AutoDiscovered
        Enabled: true
    Configuration:
      Steps:
        - Run: pip install -r requirements.txt
        - Run: echo "No test coverage step"
  CDKBootstrapAction:
    Identifier: aws/cdk-bootstrap@v1
    Environment:
      Connections:
        - Role: CodeCatalystWorkflowDevelopmentRole-awssummit-2024
          Name: "653738050483"
      Name: default_environment
    Inputs:
      Sources:
        - WorkflowSource
    Compute:
      Type: Lambda
    Configuration:
      Region: us-west-2
      CdkCliVersion: 2.114.1
  CDKDeploy:
    Identifier: aws/cdk-deploy@v1
    Environment:
      Connections:
        - Role: CodeCatalystWorkflowDevelopmentRole-awssummit-2024
          Name: "653738050483"
      Name: default_environment
    Inputs:
      Sources:
        - WorkflowSource
    Compute:
      Type: EC2
    Configuration:
      StackName: AwsSummit2024Stack-ncnxu
      Region: us-west-2
      CdkCliVersion: 2.114.1
      Context: '{"stack_name":"AwsSummit2024Stack-ncnxu"}'
    DependsOn:
      - CDKBootstrapAction
      - BuildAndTest
